### ISSUE TITLE
PM 0.8.0 todo list

### ISSUE THREAD

**Issue by forresto** [the-grid/ed#242]
https://discuss.prosemirror.net/t/release-0-8-0/336
- [x] redo ./schema/media `Media.register`
- [x] redo ./convert/grid-to-doc `fromDOM`
- [x] redo ./commands/index `CommandSet`
- [x] redo ./inputrules/autoinput.js
- [x] redo ./components/editable `autoinput`
- [x] redo ./menu/ed-menu
- [x] ./plugins/... `UpdateScheduler`
- [x] ./plugins/commands-interface
- [x] ./components/editable `this.pm.on('ed.menu.file'...`
- [ ] ./schema/media widget copy and paste

**Comment by forresto** [comment]
This update is a little painful, but probably good. PM's plugin interface is simple, pretty similiar to how I was wiring in stuff before.

Should see some perf++ from refactoring plugins to only read OR write dom at a time with PM's http://prosemirror.net/version/0.8.0.html#ProseMirror.scheduleDOMUpdate

**Comment by forresto** [comment]
![widgets](https://cloud.githubusercontent.com/assets/395307/16172008/6f2bbf1e-354c-11e6-8d7e-05785f7ce9b8.png) :metal:
